spring:
  profiles:
    active: test
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=MySQL
    password: sa
    username: sa
    driver-class-name: "org.h2.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      "[hibernate.generate_statistics]": false